# data
data:
  instruct_data: "/path/to/cleaned_onlyfans_dataset.jsonl"  # Update with your dataset path
  data: ""  # No pretraining data used
  eval_instruct_data: "/path/to/onlyfans_eval_dataset.jsonl"  # Optionally update if you have a validation set

# model
model_id_or_path: "/path/to/mistral_models/7B_instruct"  # Update with your model path
lora:
  rank: 64

# optim
seq_len: 32768
batch_size: 1
max_steps: 500
optim:
  lr: 3e-4
  weight_decay: 0.01
  pct_start: 0.05

# other
seed: 0
log_freq: 1
eval_freq: 100
no_eval: False
ckpt_freq: 100

save_adapters: True  # save only trained LoRA adapters. Set to `False` to merge LoRA adapter into the base model and save full fine-tuned model

run_dir: ""  # Fill

wandb:
  project: "suada" # your wandb project name
  run_name: "onlyfans_tune" # your wandb run name
  key: "35a03d1d2de16b755251b46657e20294b34e1305" # your wandb api key
  offline: False
